### PR TITLE
Convert CreatedBy and Contact lists to strings

### PR DESCRIPTION
**Pull request by duckontheweb**
Changes the `Contact` field in `sen12floods.yaml` and the `CreatedBy` field in `idiv_asia_crop_types.yaml` to strings. These should show up as Markdown lists when rendered.

Fixes [ME-573](https://radiantearth.atlassian.net/browse/ME-573?atlOrigin=eyJpIjoiMDkzODllYTE0ZGVhNDliMmFkMTllYTM0ZmE2ODU0NDIiLCJwIjoiaiJ9)

### CODE REVIEW

**Comment by duckontheweb** [comment]
@kbgg Should I change this PR to be against `dev` or does it not matter?

**Comment by guidorice** [comment]
@duckontheweb would you change it to be just a string without markup? Comma separated values would be OK. I looked through the other dataset's Contact fields and they are are just string, without any markdown formatting.

Also yes, I was going to ask about the `dev` vs `master`. I ran into issues with my last PR on this repo- Kevin may be able to advise on the best git flow.

**Comment by duckontheweb** [comment]
@guidorice I changed those fields to be comma-separated strings and updated the PR to be against `dev` since that seemed to be the pattern.

**Review by guidorice — APPROVED** [review]
👍🏽

**Pull request merged**
